version: '3'
services:
  #Applicazione web NextJS
  app-nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app-nextjs
    hostname: app-nextjs
    restart: always
    ports:
      -"80:3000"
    networks:
      - network-prova
    
  # Servizio PostgreSQL
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    hostname: postgres-db # Imposta il nome host per il container PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: db-nextapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - network-prova
    volumes:
      - ./data:/var/lib/postgresql/data

  # Servizio PGAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: my-pgadmin # Imposta il nome host per il container PGAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - network-prova
networks:
  network-prova:
    driver: bridge