version: '3'

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: utenteProva
      POSTGRES_PASSWORD: passwordProva
      POSTGRES_DB: db_nextapp
    ports:
      - "5432:5432"

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  next-app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    hostname: next-app
    container_name: next-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://utenteprova:utenteprova@postgres:5432/db_nextapp?schema=public
    command: bash -c "npx prisma db push && npm run dev"
