version: '3'
services:
    
  # Servizio PostgreSQL
  # pgdb:
  #   image: postgres:latest
  #   container_name: pgdb
  #   hostname: pgdb # Imposta il nome host per il container PostgreSQL
  #   restart: always
  #   environment:
  #     POSTGRES_DB: db-nextapp
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - next-app-network
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  
    #Applicazione web NextJS
  app-nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app-nextjs
    hostname: app-nextjs
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - pgdb
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@pgdb:5432/db-nextapp?schema=public"
    networks:
      - prova_next-app-network
  
  # Servizio PGAdmin
#   pgadmin:
#     image: dpage/pgadmin4:latest
#     container_name: pgadmin
#     hostname: my-pgadmin # Imposta il nome host per il container PGAdmin
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@example.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "5050:80"
#     depends_on:
#       - pgdb
#     networks:
#       - next-app-network

# networks:
#  next-app-network:
#   driver: bridge